apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: api-ingress
  namespace: api-namespace
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
  - http:
      paths:
      - backend:
          serviceName: trips
          servicePort: 80
        path: /api/trip
      - backend:
          serviceName: userprofile
          servicePort: 80
        path: /api/user
      - backend:
          serviceName: user-java
          servicePort: 80
        path: /api/user-java
      - backend:
          serviceName: poi
          servicePort: 80
        path: /api/poi
      - backend:
          serviceName: trips
          servicePort: 80
        path: /api/healthcheck/trips
      - backend:
          serviceName: userprofile
          servicePort: 80
        path: /api/healthcheck/user
      - backend:
          serviceName: poi
          servicePort: 80
        path: /api/healthcheck/poi
      - backend:
          serviceName: user-java
          servicePort: 80
        path: /api/healthcheck/user-java
      - backend:
          serviceName: trips
          servicePort: 80
        path: /api/docs/trips
      - backend:
          serviceName: userprofile
          servicePort: 80
        path: /api/docs/user
      - backend:
          serviceName: poi
          servicePort: 80
        path: /api/docs/poi
      - backend:
          serviceName: user-java
          servicePort: 80
        path: /api/docs/user-java