apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-java
  namespace: api-namespace
  labels:
    app: user-java
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-java
  template:
    metadata:
      labels:
        app: user-java
        aadpodidbinding: backend
        istio-injection: enabled
    spec:
      containers:
      - name: user-java
        image: registryet76720.azurecr.io/user-java:latest
        volumeMounts:
          - name: keyvaultflexvolume
            mountPath: /secrets
            readOnly: true
        resources:
          limits:
            memory: 256Mi
            cpu: 500m
        ports:
        - containerPort: 80
      volumes:
        - name: keyvaultflexvolume
          flexVolume:
            driver: "azure/kv"
            options:
              usepodidentity: "true"
              keyvaultname: "bestteam"
              keyvaultobjectnames: "SQLUSER;SQLPASSWORD;SQLSERVER;SQLDBNAME"
              keyvaultobjectaliases: "SQL_USER;SQL_PASSWORD;SQL_SERVER;SQL_DBNAME"
              keyvaultobjecttypes: secret;secret;secret;secret
              keyvaultobjectversions: ""
              resourcegroup: "teamResources"
              subscriptionid: "b59213bd-a592-44a1-8a94-b56694e27536"
              tenantid: "2a41c9ac-10a5-4984-ad23-e13a5018fc2e"
---
apiVersion: v1
kind: Service
metadata:
  namespace: api-namespace
  name: user-java
spec:
  selector:
    app: user-java
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
